android: PLATFORM=android -r features/support -r features/step_definitions -r features/android/pages -r features/android/support

ios: PLATFORM=ios APP_BUNDLE_PATH=apps/ios/my-calculator.app -r features/support -r features/step_definitions -r features/ios/pages
